trigger: none
pool: Vinav

stages:
  - stage: terraformdownload
    
    jobs:
      - job: terraformdownload

        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)dev'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'Batch18'
            backendAzureRmResourceGroupName: 'vinav'
            backendAzureRmStorageAccountName: 'vinavstg'
            backendAzureRmContainerName: 'test'
            backendAzureRmKey: 'terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)dev'
            environmentServiceNameAzureRM: 'Batch18'