apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:trixie-perl
    ports:
    - containerPort: 80
  volumemounts:
  - name: nginx-volume
    mountpath: /usr/share/nginx/html

  volumes:
  - name: nginx-volume
    persistentvolumeclaim:
      claimname: nginx-pvc