apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
stringData:
  azurestorageaccountname: vinav123
  azurestorageaccountkey: Wwn/wPPNQZcgnM3SLD76U3FkwfJo9S7wmBucUBWEDcPy2LCrrQo8yVtF+MOW8S6Eb4YnQGrz4qhl+ASthUjeiQ==